<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class QueryMemberAndCommodityListController extends Controller
{
    //
    public function getData()
    {
        $arr = [
            'Code' => 1,
            'ErrorMsg' => '',
            'UserArray' => [
                'Account' => 'BAA1330',
                'AllDayRemaingDayLimit' => '99',
                'AllRemainingLimit' => '1',
                'AllStoreLimit' => '3',
                'ContrastPoint' => '10000',
                'DaySubmitLimit' => '3',
                'DeleteConfirm' => '1',
                'EndTime' => '13:50:00',
                'Money' => '50000',
                'Name' => 'Y1330',
                'PointOrTodayMoney' => '0',
                'State' => '正常',
                'SubmitNotConfirm' => '1',
                'SuperPoint' => '100000',
                'TodayMoney' => '0',
                'TouchPoint' => '50000',
            ],
            'CommidyArray' => [
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '150',
                    'ID' => 'TXF',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '台指期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '正常',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '08=>45~13=>45',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '500',
                    'ID' => 'HSI',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '恆生期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '09:15~12:00<br>↵13:00~16:30<br>↵午盤17:15~次日01:00<br/>',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '300',
                    'ID' => 'E7',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '歐元期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '800',
                    'ID' => 'NK225',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '日經期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '07:45~14:15<br>↵15:30~次日04:30',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '300',
                    'ID' => 'FDAX',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '德指',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '14:00~次日04:00(冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '200',
                    'ID' => 'YM',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '道瓊期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '正常',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '300',
                    'ID' => 'CL',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '輕油期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '300',
                    'ID' => 'GC',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '黃金期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '800',
                    'ID' => 'SI',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '白銀期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '500',
                    'ID' => 'CIF',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '滬深期',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '09:30~11:30<br> 13:00~15:00',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '150',
                    'ID' => 'TXFAF',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '台盤後',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '15:00~次日05:00',
                ],
                [
                    'Closing' => '1',
                    'CoverPercent' => '7',
                    'DayCover' => '1',
                    'Fee' => '250',
                    'ID' => 'NQ',
                    'Lighting' => '1',
                    'Limiting' => '1',
                    'Name' => '那斯達',
                    'NotNewPercent' => '5',
                    'OpenMaxPoint' => '150',
                    'PointMoney' => '200',
                    'RemaingDayLimit' => '99',
                    'RemaingLimit' => '1',
                    'State' => '停權',
                    'StopPoint' => '0',
                    'StoreLimit' => '3',
                    'SubmitMax' => '3',
                    'SubmitMaxPoint' => '0',
                    'Submiting' => '-1',
                    'TradePoint' => '1',
                    'TradeTime' => '06:00~次日05:00 (冬令延1小時)',
                ],
            ],
        ];

        return response()->json($arr);
    }
}
